name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff coverage

    - name: Check code formatting
      run: |
        ruff format --check .

    - name: Lint with ruff
      run: |
        ruff check .

    - name: Check for unused imports
      run: |
        ruff check --select F401 .

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build libboost-all-dev libopenmpi-dev libnetcdf-dev libhdf5-dev libnetcdf-c++4-dev libgsl-dev pkg-config

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install netCDF4
        pip install -e ".[dev]"
        pip install coverage
      env:
        NETCDF_DIR: /usr
        HDF5_DIR: /usr
        GSL_DIR: /usr

    - name: Run tests
      run: |
        python -m coverage run -m unittest discover tests/
        python -m coverage xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella

  docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build libboost-all-dev libnetcdf-dev libhdf5-dev libnetcdf-c++4-dev libgsl-dev pkg-config

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install netCDF4
        pip install -e .
        pip install -r docs/requirements.txt
      env:
        NETCDF_DIR: /usr
        HDF5_DIR: /usr
        GSL_DIR: /usr

    - name: Build documentation
      run: |
        cd docs
        make html
